
/**
 * Extra modifications to Marlin for LulzBot printers
 */
//#define SOURCE_CODE_URL
//#define TOOLHEAD_NAME
//#define TOOLHEAD_TYPE
//#define WIPE_SEQUENCE_COMMANDS
//#define AXIS_LEVELING_COMMANDS
//#define PARK_AND_RELEASE_COMMANDS
//#define CALIBRATION_COMMANDS
//#define BED_LEVELING_COMMANDS
//#define AO_EXP1_DEPRECATED_PINMAP
//#define DISABLE_DUE_SD_MMC
//#define EXTRUDER_FAN_ON_PIN_6
//#define ACTION_ON_FILAMENT_RUNOUT
//#define ARCHIM2_SPI_FLASH_EEPROM_BACKUP_SIZE
//#define END_G29_ON_BACK_LEFT_CORNER
//#define USB_DEVICE_VENDOR_ID
//#define USB_DEVICE_PRODUCT_ID
//#define NO_PAUSE_FOR_REHEAT
//#define CURA_LE_RUNOUT_HANDLING_WORKAROUND
//#define E_MIN_PIN
//#define E_MIN_PIN_INVERTING
//#define E_MAX_POS
//#define NO_TOOLHEAD_HEATER_GCODE
//#define DEVELOPER_SCREENS
//#define TOUCH_UI_NO_BOOTSCREEN
//#define TOUCH_UI_LULZBOT_BIO
//#define TOUCH_UI_FROZEN_THEME
//#define TOUCH_UI_ROYAL_THEME
//#define SWAP_E0_AND_E1
//#define FILAMENT_RUNOUT_ENABLE_DEFAULT
//#define FIL_RUNOUT_PIN
//#define CONTROLLER_FAN_IGNORE_Z
